
Class Main{
    public static void main(String[] args) {
        // Book b1 = new Book();
        // System.out.println(b1.getShortName());
       
        // Book b2 = new Book("author", "title", 100);
        // System.out.println(b2.getShortName());

        // PrintedBook pbook1 = new PrintedBook();
        // System.out.println(pbook1.getShortName());
        // System.out.println("price = " + pbook1.getPrice());

        // PrintedBook pbook2 = new PrintedBook("author", "Printed: title", 100);
        ColoredPoint point1 = ColoredPoint(1, 3, Color.Blue);
        System.out.println(point1);

        ColoredCircle colCircle1 = ColoredCircle(point1, 12);
        System.out.println(colCircle1);

    }
}